### ISSUE TITLE
Trick people into creating a new poll while not logged in

### ISSUE THREAD

**Issue by lkuessner** [Eko450-eng/decider#14]
Instead of the "Sign Up" Icon we should stick with the "+" and react internally to if the user is logged in or not.

![image](https://user-images.githubusercontent.com/48736630/234822221-360c38ba-1e49-4e62-ae2d-670020fbe487.png)

Keep this as default

**Comment by Eko450-eng** [comment]
Implemented in next version (I think that's what you meant)
